apiVersion: v1
kind: PersistentVolume
metadata:
  name: scylla-2
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: scylla-ssd
  local:
    path: /var/lib/scylla-2
  nodeAffinity:                          
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - minikube 
